"use client";

import { useEffect, useMemo, useState } from "react";
import WarRoomArsenalIcon from "@/components/WarRoomArsenalIcon";
import { authorizeFoundryJdam, generateNflPlayoffPicks, nflBracketComplete, nflPlayoffGames, sanitizeNflPlayoffPicks, type NflPlayoffPicks } from "@/lib/postseason/nfl-maps";

type Lab = { picks: NflPlayoffPicks; locked: boolean; original: NflPlayoffPicks | null; targets: string[]; changedCount: number; reviewed: boolean };
const KEY = "warroom-foundry-nfl-maps-v1";
const fresh = (): Lab => ({ picks: {}, locked: false, original: null, targets: [], changedCount: 0, reviewed: false });

export default function FoundryNflActThree() {
  const [lab, setLab] = useState<Lab>(fresh);
  const [ready, setReady] = useState(false);
  const [step, setStep] = useState(0);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(KEY) || "null"); if (saved?.picks) setLab(saved); } catch {} setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem(KEY, JSON.stringify(lab)); }, [ready, lab]);
  const games = nflPlayoffGames(lab.picks);
  const complete = nflBracketComplete(lab.picks);
  const next = games.find((game) => !lab.picks[game.id]);
  const champion = games.find((game) => game.id === "super-bowl")?.teams.find((team) => team.id === lab.picks["super-bowl"]);
  const names = useMemo(() => new Map(nflPlayoffGames(generateNflPlayoffPicks(1)).flatMap((game) => game.teams.map((team) => [team.id, team.name]))), []);
  function choose(id: string, teamId: string) { if (lab.locked) return; setLab((current) => ({ ...current, picks: sanitizeNflPlayoffPicks({ ...current.picks, [id]: teamId }) })); }
  function jdam() { const result = authorizeFoundryJdam(lab.picks); if (!result.targets.length) return; setStep(0); setLab({ picks: result.picks, locked: true, original: { ...lab.picks }, targets: result.targets, changedCount: result.changedCount, reviewed: false }); }
  async function share() { const text = `I authorized M.A.P.’s JDAM Protocol. ${lab.changedCount} NFL playoff decisions changed. My bracket no longer reflects my personal beliefs.`; if (navigator.share) await navigator.share({ title: "War Room JDAM Damage Assessment", text }); else await navigator.clipboard?.writeText(text); }
  if (!ready) return <p className="rounded-2xl border border-border p-5 text-center text-xs">Opening the playoff operations center…</p>;
  const reviewDone = step >= lab.targets.length;
  const target = lab.targets[Math.min(step, lab.targets.length - 1)];
  return <section className="space-y-4"><header className="rounded-2xl border border-sky-300/40 bg-[radial-gradient(circle_at_top,#0c4a6e,#020617_65%)] p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-sky-300">NFL Act III · Foundry only</p><h3 className="mt-1 text-2xl font-black">The Road to the Bowl</h3><p className="mt-2 text-xs text-muted">Fourteen teams. Thirteen decisions. The lowest remaining seed visits the 1-seed in each divisional round.</p><div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Decisions" value={`${Object.keys(lab.picks).length}/13`}/><Metric label="Champion" value={champion?.name || "TBD"}/></div></header>
    {!lab.locked && <div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setLab((current) => ({ ...current, picks: generateNflPlayoffPicks(1) }))} className="min-h-11 rounded-xl border border-sky-300/40 text-[10px] font-black text-sky-200">Foundry autofill 13</button><button type="button" disabled={!complete} onClick={() => setLab((current) => ({ ...current, locked: true }))} className="min-h-11 rounded-xl bg-sky-300 text-[10px] font-black text-sky-950 disabled:opacity-35">Lock playoff bracket</button></div>}
    {complete && !lab.locked && <button type="button" onClick={jdam} className="flex min-h-16 w-full items-center justify-center gap-3 rounded-2xl border-2 border-blue-400 bg-[repeating-linear-gradient(135deg,#061a38_0,#061a38_12px,#020617_12px,#020617_24px)] px-4 text-sm font-black text-blue-100 shadow-[0_0_35px_rgba(96,165,250,.4)]"><WarRoomArsenalIcon kind="jdam" size={54}/><span><small className="block text-[8px] uppercase tracking-[.2em] text-blue-300">M.A.P.’s · Mutually Assured Picks</small>AUTHORIZE JDAM PROTOCOL</span></button>}
    <div className="grid gap-3 sm:grid-cols-2">{games.map((game) => <article key={game.id} className={`rounded-xl border p-3 ${lab.picks[game.id] ? "border-sky-300/35 bg-sky-950/15" : next?.id === game.id ? "border-amber-300/60 bg-amber-950/15" : "border-border bg-card opacity-60"}`}><p className="text-[8px] font-black uppercase tracking-[.16em] text-sky-300">{game.label}</p><div className="mt-2 space-y-1">{game.teams.map((team) => <button key={team.id} type="button" disabled={lab.locked} onClick={() => choose(game.id, team.id)} className={`flex min-h-10 w-full items-center justify-between rounded-lg border px-3 text-left text-[10px] font-bold ${lab.picks[game.id] === team.id ? "border-sky-300 bg-sky-300 text-sky-950" : "border-white/10"}`}><span>{team.seed} · {team.name}</span><span>{lab.picks[game.id] === team.id ? "ADV" : ""}</span></button>)}</div></article>)}</div>
    {lab.original && lab.reviewed && <section className="rounded-2xl border-2 border-blue-400/60 bg-blue-950/25 p-4 text-center"><WarRoomArsenalIcon kind="maps" size={72}/><p className="mt-2 text-[9px] font-black uppercase tracking-[.2em] text-blue-300">JDAM damage assessment</p><h4 className="mt-1 text-xl font-black">PRECISION WAS CLAIMED. CONSEQUENCES WERE DELIVERED.</h4><p className="mt-2 text-xs text-muted">{lab.changedCount} of 13 decisions changed · champion: {champion?.name}</p><button type="button" onClick={() => void share()} className="mt-3 min-h-12 w-full rounded-xl border border-blue-300/50 text-xs font-black text-blue-200">SHARE THE EVIDENCE ↗</button></section>}
    {lab.original && !lab.reviewed && <div className="fixed inset-0 z-[85] flex items-end justify-center bg-[#020b1c]/95 p-4 backdrop-blur-sm sm:items-center" role="dialog" aria-modal="true"><section className="w-full max-w-md rounded-3xl border-2 border-blue-400 bg-[radial-gradient(circle_at_top,#0c4a6e,#020617_65%)] p-5 text-center shadow-[0_0_100px_rgba(96,165,250,.5)]"><WarRoomArsenalIcon kind={reviewDone ? "maps" : "jdam"} size={92}/>{reviewDone ? <><p className="mt-3 text-[9px] font-black uppercase tracking-[.2em] text-blue-300">Target package complete</p><h3 className="mt-2 text-3xl font-black">BATTLE DAMAGE ASSESSMENT</h3><p className="mt-3 text-sm text-white/70">{lab.changedCount} bracket decisions changed. Original targeting plan preserved for the investigation.</p><button type="button" onClick={() => setLab((current) => ({ ...current, reviewed: true }))} className="mt-5 min-h-14 w-full rounded-xl bg-blue-300 text-sm font-black text-blue-950">I HAVE SEEN THE DAMAGE</button></> : <><p className="mt-3 text-[9px] font-black uppercase tracking-[.2em] text-blue-300">JDAM {step + 1} OF {lab.targets.length}</p><p className="mt-4 text-sm text-muted">ORIGINAL TARGET</p><h3 className="text-2xl font-black">{names.get(lab.original[target]) || lab.original[target]}</h3><div className="my-3 text-3xl text-red-400">⌖</div><p className="text-sm text-muted">COMPUTER SOLUTION</p><h3 className="text-2xl font-black text-blue-200">{names.get(lab.picks[target]) || lab.picks[target]}</h3><button type="button" onClick={() => setStep((value) => value + 1)} className="mt-5 min-h-14 w-full rounded-xl bg-blue-300 text-sm font-black text-blue-950">{step + 1 === lab.targets.length ? "RUN DAMAGE ASSESSMENT" : "VIEW NEXT IMPACT"}</button></>}</section></div>}
    <button type="button" onClick={() => { localStorage.removeItem(KEY); setLab(fresh()); setStep(0); }} className="min-h-11 w-full rounded-xl border border-red-400/30 text-xs font-bold text-red-200">Reset NFL Act III Lab</button>
  </section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-black/30 p-2 text-center"><strong className="block truncate text-sm">{value}</strong><span className="text-[8px] font-black uppercase tracking-wide text-muted">{label}</span></div>; }
