import PublicPolicyPage from "@/components/PublicPolicyPage";

export const metadata = { title: "Privacy Policy · War Room Pick'Em" };
export default function PrivacyPage() { return <PublicPolicyPage title="Privacy Policy">
  <section><h2>What War Room collects</h2><ul><li>Account information such as email address and authentication identifiers.</li><li>Profile information you provide, including display name, avatar, birthday month/day, and favorite teams.</li><li>League membership, picks, scores, standings, achievements, and commissioner settings needed to run the game.</li><li>Locker Room posts, reactions, uploaded media, and reports or blocks you submit.</li><li>Limited operational records needed for reliability, security, and abuse prevention.</li></ul></section>
  <section><h2>How it is used</h2><p>We use this information to authenticate you, operate private friend leagues, calculate results, display league history, support social features, respond to support requests, and protect players and the service. War Room does not sell personal information or use third-party advertising networks.</p></section>
  <section><h2>Storage and sharing</h2><p>War Room uses Supabase for authentication, database, and file storage infrastructure. Information is shared with service providers only as needed to operate and secure the product, or when required by law. League content is shown according to membership and moderation rules.</p></section>
  <section><h2>Retention and deletion</h2><p>Account and league records are retained while needed to provide the service, preserve legitimate season history, resolve abuse or security issues, and meet legal obligations. You may request account deletion by contacting support. Commissioner-owned leagues may need to be transferred or closed first. Deletion removes or anonymizes personal data where required while allowing non-personal competitive records to remain coherent.</p></section>
  <section><h2>Your choices</h2><p>You can edit profile information, leave leagues, delete your own Locker posts where available, block players, and report abuse. To request access, correction, or deletion, email <a className="text-primary underline" href="mailto:michaelvance2430@gmail.com">michaelvance2430@gmail.com</a>.</p></section>
  <section><h2>Security and changes</h2><p>We use access controls and row-level security designed to limit data to authorized users. No system is perfectly secure. Material policy changes will be reflected on this page with a new effective date.</p></section>
</PublicPolicyPage>; }
