import PublicPolicyPage from "@/components/PublicPolicyPage";

export const metadata = { title: "Privacy Policy · War Room Pick'Em" };
export default function PrivacyPage() { return <PublicPolicyPage title="Privacy Policy" updated="August 18, 2026">
  <section><h2>What War Room collects</h2><ul><li>Account information such as email address and authentication identifiers.</li><li>Profile information you provide, including display name, avatar, birthday month/day, and favorite teams.</li><li>League membership, picks, scores, standings, achievements, and commissioner settings needed to run the game.</li><li>Locker Room posts, reactions, uploaded media, and reports or blocks you submit.</li><li>Limited operational records needed for reliability, security, and abuse prevention.</li></ul></section>
  <section><h2>How it is used</h2><p>We use this information to authenticate you, operate private friend leagues, calculate results, display league history, support social features, respond to support requests, and protect players and the service. War Room does not sell personal information or use third-party advertising networks.</p></section>
  <section><h2>Storage and sharing</h2><p>War Room uses Supabase for authentication, database, and file storage, Vercel for application hosting and operational delivery, sports-data providers for schedules, odds, and final scores, and AI service providers for commissioner-requested Dispatch generation. These processors receive only the information needed to provide their service. War Room does not sell personal information, use third-party advertising networks, or permit cross-app tracking. League content is shown according to membership and moderation rules.</p></section>
  <section><h2>Retention and deletion</h2><p>Account and private profile data are retained while your account is active. Locker posts and uploads remain until you delete them, a moderator removes them, their league is removed, or you delete your account. Security and abuse records are retained only as reasonably necessary to investigate and prevent misuse or meet legal obligations. Selecting Delete account in Account settings removes your login, sessions, avatar, uploads, Locker content, birthday, favorite teams, and other private identity data. Non-identifying picks, scores, standings, trophies, brackets, and league history remain under [REDACTED] so other players&apos; completed seasons remain coherent. Commissioners must transfer each room before deletion.</p></section>
  <section><h2>Your choices</h2><p>You can edit profile information, leave leagues, delete your Locker posts, block players, and report abuse. You can permanently delete your account from Account → Delete account. For access, correction, privacy questions, or help with a failed deletion, email <a className="text-primary underline" href="mailto:mike@war-room-picks.com">mike@war-room-picks.com</a>.</p></section>
  <section><h2>Security and changes</h2><p>We use access controls and row-level security designed to limit data to authorized users. No system is perfectly secure. Material policy changes will be reflected on this page with a new effective date.</p></section>
</PublicPolicyPage>; }
