/**
 * FIFA Women's World Cup Brazil 2027™ achievements.
 * Tournament magic — not CFB grind. Passport stamps, not football medals.
 */

import type { BadgeDef, BadgeTier } from "@/lib/types";
import { TIER_POINTS } from "@/lib/badges";

/** Passport stamp art keys (UI maps to stamp chrome) */
export type WwcStampKind =
  | "visa"
  | "ticket"
  | "globe"
  | "lion"
  | "stadium"
  | "brazil"
  | "trophy"
  | "gold_seal";

export type WwcBadgeDef = BadgeDef & {
  sportId: "soccer_wwc";
  stamp: WwcStampKind;
  /** How far we can auto-evaluate today */
  evalReady: "live" | "partial" | "stub";
};

function b(
  partial: Omit<WwcBadgeDef, "points" | "sportId" | "lockedLabel"> & {
    points?: number;
  }
): WwcBadgeDef {
  return {
    ...partial,
    sportId: "soccer_wwc",
    points: partial.points ?? TIER_POINTS[partial.tier],
    lockedLabel: partial.howToEarn,
  };
}

const stampForTier = (tier: BadgeTier, i: number): WwcStampKind => {
  if (tier === "legendary") return i % 2 === 0 ? "gold_seal" : "trophy";
  if (tier === "epic") return (["trophy", "brazil", "globe"] as const)[i % 3];
  if (tier === "rare") return (["lion", "stadium", "globe"] as const)[i % 3];
  return (["visa", "ticket", "globe"] as const)[i % 3];
};

/** 35 Common */
const COMMON: WwcBadgeDef[] = [
  b({
    id: "wwc_welcome_pitch",
    name: "Welcome to the Pitch",
    description: "You made it to the World Cup room. Boots on.",
    howToEarn: "Create your account.",
    tier: "common",
    icon: "⚽",
    stamp: "visa",
    evalReady: "live",
  }),
  b({
    id: "wwc_world_traveler",
    name: "World Traveler",
    description: "First stamp in the passport — you joined a Cup league.",
    howToEarn: "Join your first World Cup league.",
    tier: "common",
    icon: "✈️",
    stamp: "visa",
    evalReady: "live",
  }),
  b({
    id: "wwc_kickoff",
    name: "Kickoff",
    description: "First card locked. The tournament notices.",
    howToEarn: "Submit your first World Cup picks.",
    tier: "common",
    icon: "🏁",
    stamp: "ticket",
    evalReady: "live",
  }),
  b({
    id: "wwc_groupie",
    name: "Groupie",
    description: "Every group matchday handled. No ghosts in the group.",
    howToEarn: "Complete all Group Stage picks.",
    tier: "common",
    icon: "📋",
    stamp: "ticket",
    evalReady: "stub",
  }),
  b({
    id: "wwc_matchday_ready",
    name: "Matchday Ready",
    description: "Locked before the whistle. Professional tourist energy.",
    howToEarn: "Lock picks before kickoff.",
    tier: "common",
    icon: "🔒",
    stamp: "visa",
    evalReady: "partial",
  }),
  b({
    id: "wwc_flag_bearer",
    name: "Flag Bearer",
    description: "First nation cashed. The flag goes up.",
    howToEarn: "Pick your first nation correctly.",
    tier: "common",
    icon: "🏳️",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_continental_drift",
    name: "Continental Drift",
    description: "Four continents on the card. Passport getting heavy.",
    howToEarn: "Correctly pick teams from four different continents.",
    tier: "common",
    icon: "🌍",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_european_expert",
    name: "European Expert",
    description: "UEFA homework graded. Gold stars optional.",
    howToEarn: "Correctly predict 10 UEFA teams.",
    tier: "common",
    icon: "🇪🇺",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_south_american_specialist",
    name: "South American Specialist",
    description: "CONMEBOL reads. Host continent energy.",
    howToEarn: "Correctly predict 10 CONMEBOL teams.",
    tier: "common",
    icon: "🌎",
    stamp: "brazil",
    evalReady: "stub",
  }),
  b({
    id: "wwc_giant_of_africa",
    name: "Giant of Africa",
    description: "CAF correctness. Respect the continent.",
    howToEarn: "Correctly predict 5 CAF teams.",
    tier: "common",
    icon: "🦁",
    stamp: "lion",
    evalReady: "stub",
  }),
  b({
    id: "wwc_asian_ace",
    name: "Asian Ace",
    description: "AFC board knowledge, not vibes alone.",
    howToEarn: "Correctly predict 5 AFC teams.",
    tier: "common",
    icon: "🥋",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_concacaf_supporter",
    name: "CONCACAF Supporter",
    description: "Region locked in. Chaos optional.",
    howToEarn: "Correctly predict 5 CONCACAF teams.",
    tier: "common",
    icon: "🗽",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_oceania_observer",
    name: "Oceania Observer",
    description: "OFC got a W on your card. Rare air.",
    howToEarn: "Correctly predict an OFC victory.",
    tier: "common",
    icon: "🌊",
    stamp: "visa",
    evalReady: "stub",
  }),
  b({
    id: "wwc_draw_master",
    name: "Draw Master",
    description: "Five correct draws. The most annoying kind of right.",
    howToEarn: "Correctly predict five draws.",
    tier: "common",
    icon: "🤝",
    stamp: "ticket",
    evalReady: "stub",
  }),
  b({
    id: "wwc_home_stretch",
    name: "Home Stretch",
    description: "Group stage complete. Knockouts loading.",
    howToEarn: "Finish the Group Stage.",
    tier: "common",
    icon: "📦",
    stamp: "ticket",
    evalReady: "stub",
  }),
  b({
    id: "wwc_bracket_begins",
    name: "Bracket Begins",
    description: "R16 card filed. No more group therapy.",
    howToEarn: "Complete Round of 16 picks.",
    tier: "common",
    icon: "🗂️",
    stamp: "ticket",
    evalReady: "stub",
  }),
  b({
    id: "wwc_quarterfinal_bound",
    name: "Quarterfinal Bound",
    description: "QF slate locked. Pressure rising.",
    howToEarn: "Complete Quarterfinal picks.",
    tier: "common",
    icon: "8️⃣",
    stamp: "stadium",
    evalReady: "stub",
  }),
  b({
    id: "wwc_semifinalist",
    name: "Semifinalist",
    description: "Final four energy on the card.",
    howToEarn: "Complete Semifinal picks.",
    tier: "common",
    icon: "4️⃣",
    stamp: "stadium",
    evalReady: "stub",
  }),
  b({
    id: "wwc_final_countdown",
    name: "Final Countdown",
    description: "The Final is on your card. History loading.",
    howToEarn: "Submit Final picks.",
    tier: "common",
    icon: "⏱️",
    stamp: "trophy",
    evalReady: "stub",
  }),
  b({
    id: "wwc_champion_chosen",
    name: "Champion Chosen",
    description: "You named a world champion. Bold.",
    howToEarn: "Pick a World Champion.",
    tier: "common",
    icon: "🏆",
    stamp: "trophy",
    evalReady: "stub",
  }),
  b({
    id: "wwc_golden_boot_guess",
    name: "Golden Boot Guess",
    description: "Golden Boot ticket stamped.",
    howToEarn: "Make a Golden Boot prediction.",
    tier: "common",
    icon: "👟",
    stamp: "gold_seal",
    evalReady: "stub",
  }),
  b({
    id: "wwc_clean_sheet",
    name: "Clean Sheet",
    description: "Three shutouts called. Defensive scouting.",
    howToEarn: "Correctly predict three shutouts.",
    tier: "common",
    icon: "🧤",
    stamp: "ticket",
    evalReady: "stub",
  }),
  b({
    id: "wwc_hat_trick",
    name: "Hat Trick",
    description: "Three straight matches cashed.",
    howToEarn: "Correctly predict three consecutive matches.",
    tier: "common",
    icon: "🎩",
    stamp: "visa",
    evalReady: "partial",
  }),
  b({
    id: "wwc_onside",
    name: "Onside",
    description: "Three matchdays, no ghosting.",
    howToEarn: "Submit picks three matchdays in a row.",
    tier: "common",
    icon: "📏",
    stamp: "visa",
    evalReady: "partial",
  }),
  b({
    id: "wwc_midnight_scout",
    name: "Midnight Scout",
    description: "Locked after 10 PM. Night watch on the tournament.",
    howToEarn: "Submit picks after 10 PM.",
    tier: "common",
    icon: "🌙",
    stamp: "visa",
    evalReady: "stub",
  }),
  b({
    id: "wwc_early_bird",
    name: "Early Bird",
    description: "Before 8 AM. Jet lag or dedication.",
    howToEarn: "Submit picks before 8 AM.",
    tier: "common",
    icon: "🌅",
    stamp: "visa",
    evalReady: "stub",
  }),
  b({
    id: "wwc_confidence_builder",
    name: "Confidence Builder",
    description: "Full confidence ladder used correctly.",
    howToEarn: "Use all confidence values correctly.",
    tier: "common",
    icon: "📶",
    stamp: "ticket",
    evalReady: "partial",
  }),
  b({
    id: "wwc_best_bet_winner",
    name: "Best Bet Winner",
    description: "Best Bet cashed. Double the flex.",
    howToEarn: "Hit your Best Bet.",
    tier: "common",
    icon: "💰",
    stamp: "ticket",
    evalReady: "partial",
  }),
  b({
    id: "wwc_lucky_bounce",
    name: "Lucky Bounce",
    description: "Won the week despite missing more matches than an opponent.",
    howToEarn: "Win despite missing more matches than an opponent.",
    tier: "common",
    icon: "🎲",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_flag_collector",
    name: "Flag Collector",
    description: "Fifteen different nations correct. Stamp collection growing.",
    howToEarn: "Correctly pick 15 different nations.",
    tier: "common",
    icon: "🎌",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_survivor",
    name: "Survivor",
    description: "Above league average through the groups.",
    howToEarn: "Stay above league average through Group Stage.",
    tier: "common",
    icon: "🛟",
    stamp: "ticket",
    evalReady: "stub",
  }),
  b({
    id: "wwc_pitch_perfect",
    name: "Pitch Perfect",
    description: "Every match on one matchday correct. Magic.",
    howToEarn: "Correctly predict every match on one matchday.",
    tier: "common",
    icon: "✨",
    stamp: "gold_seal",
    evalReady: "partial",
  }),
  b({
    id: "wwc_world_citizen",
    name: "World Citizen",
    description: "Winners from every confederation on the card.",
    howToEarn: "Pick winners from every confederation.",
    tier: "common",
    icon: "🌐",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_opening_ceremony",
    name: "Opening Ceremony",
    description: "There on opening matchday. Fireworks optional.",
    howToEarn: "Participate on opening matchday.",
    tier: "common",
    icon: "🎆",
    stamp: "brazil",
    evalReady: "stub",
  }),
  b({
    id: "wwc_closing_ceremony",
    name: "Closing Ceremony",
    description: "Finished the entire tournament. Passport full.",
    howToEarn: "Finish the entire tournament.",
    tier: "common",
    icon: "🎊",
    stamp: "brazil",
    evalReady: "stub",
  }),
].map((def, i) => ({ ...def, stamp: def.stamp || stampForTier("common", i) }));

/** 25 Rare */
const RARE: WwcBadgeDef[] = [
  b({
    id: "wwc_group_stage_guru",
    name: "Group Stage Guru",
    description: "Every winner in one group. Bracket-nerd heaven.",
    howToEarn: "Correctly predict every winner in one group.",
    tier: "rare",
    icon: "🧠",
    stamp: "stadium",
    evalReady: "stub",
  }),
  b({
    id: "wwc_penalty_prophet",
    name: "Penalty Prophet",
    description: "Three shootout winners called. Ice in the veins.",
    howToEarn: "Correctly predict three penalty shootout winners.",
    tier: "rare",
    icon: "🥅",
    stamp: "lion",
    evalReady: "stub",
  }),
  b({
    id: "wwc_cinderella_hunter",
    name: "Cinderella Hunter",
    description: "Three major upsets. Fairy godmother energy.",
    howToEarn: "Correctly predict three major upsets.",
    tier: "rare",
    icon: "👠",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_giant_killer",
    name: "Giant Killer",
    description: "Underdog over a Top 10 FIFA nation. History loves this.",
    howToEarn: "Correctly pick an underdog over a Top 10 FIFA nation.",
    tier: "rare",
    icon: "🗡️",
    stamp: "lion",
    evalReady: "stub",
  }),
  b({
    id: "wwc_var_survivor",
    name: "VAR Survivor",
    description: "Won after a late VAR reversal. The room will never shut up.",
    howToEarn: "Win after a late VAR reversal changes a result.",
    tier: "rare",
    icon: "📺",
    stamp: "ticket",
    evalReady: "stub",
  }),
  b({
    id: "wwc_stoppage_time_hero",
    name: "Stoppage Time Hero",
    description: "Won because of a goal after 90'. Pure cinema.",
    howToEarn: "Win because of a goal after 90'.",
    tier: "rare",
    icon: "⌚",
    stamp: "stadium",
    evalReady: "stub",
  }),
  b({
    id: "wwc_red_card_reader",
    name: "Red Card Reader",
    description: "Called a red-card match (props). Chaos certified.",
    howToEarn: "Correctly predict a match featuring a red card (if using props).",
    tier: "rare",
    icon: "🟥",
    stamp: "ticket",
    evalReady: "stub",
  }),
  b({
    id: "wwc_draw_whisperer",
    name: "Draw Whisperer",
    description: "Eight correct draws. Dark arts.",
    howToEarn: "Correctly predict eight draws.",
    tier: "rare",
    icon: "🔮",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_continental_champion",
    name: "Continental Champion",
    description: "Led the league through Group Stage.",
    howToEarn: "Lead your league through Group Stage.",
    tier: "rare",
    icon: "🥇",
    stamp: "brazil",
    evalReady: "stub",
  }),
  b({
    id: "wwc_knockout_king",
    name: "Knockout King",
    description: "Led every knockout round. Relentless.",
    howToEarn: "Lead every knockout round.",
    tier: "rare",
    icon: "👑",
    stamp: "trophy",
    evalReady: "stub",
  }),
  b({
    id: "wwc_clutch_performer",
    name: "Clutch Performer",
    description: "Won your matchup on the Final.",
    howToEarn: "Win your matchup on the Final.",
    tier: "rare",
    icon: "💎",
    stamp: "trophy",
    evalReady: "stub",
  }),
  b({
    id: "wwc_best_bet_sniper",
    name: "Best Bet Sniper",
    description: "Every knockout Best Bet hit.",
    howToEarn: "Hit every Best Bet in the knockout rounds.",
    tier: "rare",
    icon: "🎯",
    stamp: "lion",
    evalReady: "stub",
  }),
  b({
    id: "wwc_globe_trotter",
    name: "Globe Trotter",
    description: "25 different nations correct.",
    howToEarn: "Correctly predict 25 different nations.",
    tier: "rare",
    icon: "🧭",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_flags_of_the_world",
    name: "Flags of the World",
    description: "Every confederation represented correctly.",
    howToEarn: "Correctly pick teams from every confederation.",
    tier: "rare",
    icon: "🏳️‍🌈",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_comeback_complete",
    name: "Comeback Complete",
    description: "Bottom half after groups → Top 3 finish.",
    howToEarn: "Move from bottom half after groups into Top 3.",
    tier: "rare",
    icon: "📈",
    stamp: "stadium",
    evalReady: "stub",
  }),
  b({
    id: "wwc_survivors_instinct",
    name: "Survivor's Instinct",
    description: "Never missed a lock. Iron discipline.",
    howToEarn: "Never miss a lock.",
    tier: "rare",
    icon: "🦾",
    stamp: "visa",
    evalReady: "partial",
  }),
  b({
    id: "wwc_last_minute_magic",
    name: "Last Minute Magic",
    description: "Three stoppage-time winners called.",
    howToEarn: "Correctly predict three stoppage-time winners.",
    tier: "rare",
    icon: "🪄",
    stamp: "stadium",
    evalReady: "stub",
  }),
  b({
    id: "wwc_group_winner",
    name: "Group Winner",
    description: "All advancing teams from one group correct.",
    howToEarn: "Correctly predict all advancing teams from one group.",
    tier: "rare",
    icon: "🎫",
    stamp: "ticket",
    evalReady: "stub",
  }),
  b({
    id: "wwc_national_pride",
    name: "National Pride",
    description: "Favorite nation's entire group stage cashed.",
    howToEarn: "Correctly predict your favorite nation's entire group stage.",
    tier: "rare",
    icon: "❤️",
    stamp: "brazil",
    evalReady: "stub",
  }),
  b({
    id: "wwc_trophy_hunter",
    name: "Trophy Hunter",
    description: "First World Cup league win. Stamp of glory.",
    howToEarn: "Win your first World Cup league.",
    tier: "rare",
    icon: "🏆",
    stamp: "trophy",
    evalReady: "stub",
  }),
  b({
    id: "wwc_world_stage",
    name: "World Stage",
    description: "Finished Top 3. Podium energy.",
    howToEarn: "Finish Top 3.",
    tier: "rare",
    icon: "🥉",
    stamp: "gold_seal",
    evalReady: "stub",
  }),
  b({
    id: "wwc_ice_in_the_veins",
    name: "Ice in the Veins",
    description: "Every semifinal correct.",
    howToEarn: "Correctly predict every semifinal.",
    tier: "rare",
    icon: "🧊",
    stamp: "lion",
    evalReady: "stub",
  }),
  b({
    id: "wwc_extra_time_expert",
    name: "Extra Time Expert",
    description: "Multiple extra-time winners called.",
    howToEarn: "Correctly predict multiple extra-time winners.",
    tier: "rare",
    icon: "➕",
    stamp: "stadium",
    evalReady: "stub",
  }),
  b({
    id: "wwc_final_four",
    name: "Final Four",
    description: "Every semifinalist locked before knockouts.",
    howToEarn: "Correctly predict every semifinalist before knockouts.",
    tier: "rare",
    icon: "4️⃣",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_global_scout",
    name: "Global Scout",
    description: "40 matches correct. Professional tourist.",
    howToEarn: "Correctly pick 40 matches.",
    tier: "rare",
    icon: "🔭",
    stamp: "globe",
    evalReady: "partial",
  }),
];

/** 15 Epic */
const EPIC: WwcBadgeDef[] = [
  b({
    id: "wwc_world_champion",
    name: "World Champion",
    description: "Won a World Cup league. The room remembers.",
    howToEarn: "Win a World Cup league.",
    tier: "epic",
    icon: "🏆",
    stamp: "trophy",
    evalReady: "stub",
  }),
  b({
    id: "wwc_queen_of_predictions",
    name: "Queen of Predictions",
    description: "Won the Women's World Cup league.",
    howToEarn: "Win the Women's World Cup league.",
    tier: "epic",
    icon: "👸",
    stamp: "gold_seal",
    evalReady: "stub",
  }),
  b({
    id: "wwc_perfect_knockout",
    name: "Perfect Knockout",
    description: "Every knockout winner correct.",
    howToEarn: "Correctly predict every knockout winner.",
    tier: "epic",
    icon: "⚔️",
    stamp: "trophy",
    evalReady: "stub",
  }),
  b({
    id: "wwc_final_four_oracle",
    name: "Final Four Oracle",
    description: "Every semifinalist before knockouts. Oracle energy.",
    howToEarn: "Predict every semifinalist before knockouts begin.",
    tier: "epic",
    icon: "🧿",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_golden_oracle",
    name: "Golden Oracle",
    description: "Champion + Golden Boot both cashed.",
    howToEarn: "Correctly predict Champion and Golden Boot winner.",
    tier: "epic",
    icon: "🥇",
    stamp: "gold_seal",
    evalReady: "stub",
  }),
  b({
    id: "wwc_impossible_bracket",
    name: "Impossible Bracket",
    description: "Champion, Runner-up, and Third Place all correct.",
    howToEarn: "Correctly predict Champion, Runner-up, and Third Place.",
    tier: "epic",
    icon: "📊",
    stamp: "brazil",
    evalReady: "stub",
  }),
  b({
    id: "wwc_cinderella_story",
    name: "Cinderella Story",
    description: "Unexpected semifinalist called before the tournament.",
    howToEarn: "Correctly predict an unexpected semifinalist before the tournament.",
    tier: "epic",
    icon: "🏰",
    stamp: "lion",
    evalReady: "stub",
  }),
  b({
    id: "wwc_continental_master",
    name: "Continental Master",
    description: "Winners from every confederation during the tournament.",
    howToEarn: "Correctly predict winners from every confederation during the tournament.",
    tier: "epic",
    icon: "🗺️",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_never_blinked",
    name: "Never Blinked",
    description: "Never missed a lock for the entire tournament.",
    howToEarn: "Never miss a lock for the entire tournament.",
    tier: "epic",
    icon: "👁️",
    stamp: "visa",
    evalReady: "stub",
  }),
  b({
    id: "wwc_queen_of_the_world_epic",
    name: "Queen of the World",
    description: "Finished first while leading the fewest matchdays.",
    howToEarn: "Finish first while leading the fewest matchdays.",
    tier: "epic",
    icon: "👑",
    stamp: "trophy",
    evalReady: "stub",
  }),
  b({
    id: "wwc_penalty_queen",
    name: "Penalty Queen",
    description: "Every shootout correct. Absolute ice.",
    howToEarn: "Correctly predict every shootout.",
    tier: "epic",
    icon: "🧊",
    stamp: "gold_seal",
    evalReady: "stub",
  }),
  b({
    id: "wwc_global_domination",
    name: "Global Domination",
    description: "Above 85% match accuracy.",
    howToEarn: "Finish above 85% match accuracy.",
    tier: "epic",
    icon: "🌐",
    stamp: "globe",
    evalReady: "partial",
  }),
  b({
    id: "wwc_around_the_world",
    name: "Around the World",
    description: "50 matches correct. Frequent flyer.",
    howToEarn: "Correctly predict 50 matches.",
    tier: "epic",
    icon: "✈️",
    stamp: "visa",
    evalReady: "partial",
  }),
  b({
    id: "wwc_world_stage_legend",
    name: "World Stage Legend",
    description: "Won every knockout matchup in your league.",
    howToEarn: "Win every knockout matchup in your league.",
    tier: "epic",
    icon: "🌟",
    stamp: "trophy",
    evalReady: "stub",
  }),
  b({
    id: "wwc_the_last_whistle",
    name: "The Last Whistle",
    description: "Won the championship on the Final.",
    howToEarn: "Win the championship on the Final.",
    tier: "epic",
    icon: "📣",
    stamp: "brazil",
    evalReady: "stub",
  }),
];

/** 5 Legendary — four-year memory energy */
const LEGENDARY: WwcBadgeDef[] = [
  b({
    id: "wwc_immortal_champion",
    name: "⭐ Immortal Champion",
    description: "Three different World Cup tournament wins across years.",
    howToEarn: "Win three different World Cup tournaments (across years).",
    tier: "legendary",
    icon: "⭐",
    stamp: "gold_seal",
    evalReady: "stub",
  }),
  b({
    id: "wwc_the_oracle",
    name: "🌍 The Oracle",
    description: "World Champion correct in three consecutive tournaments.",
    howToEarn: "Correctly predict the World Champion in three consecutive tournaments.",
    tier: "legendary",
    icon: "🌍",
    stamp: "globe",
    evalReady: "stub",
  }),
  b({
    id: "wwc_queen_never_trailed",
    name: "🏆 Queen of the World",
    description:
      "Won the Women's World Cup league without ever trailing after Group Stage.",
    howToEarn:
      "Win the Women's World Cup league without ever trailing after Group Stage.",
    tier: "legendary",
    icon: "🏆",
    stamp: "trophy",
    evalReady: "stub",
  }),
  b({
    id: "wwc_world_cup_legend",
    name: "👑 World Cup Legend",
    description: "Every World Cup Epic achievement earned.",
    howToEarn: "Earn every World Cup Epic achievement.",
    tier: "legendary",
    icon: "👑",
    stamp: "gold_seal",
    evalReady: "stub",
  }),
  b({
    id: "wwc_one_in_a_million",
    name: "🌎 One in a Million",
    description: "Perfect tournament — every match prediction correct.",
    howToEarn: "Complete a perfect tournament (every match prediction correct).",
    tier: "legendary",
    icon: "🌎",
    stamp: "gold_seal",
    evalReady: "stub",
  }),
];

export const WWC_ACHIEVEMENT_CATALOG: WwcBadgeDef[] = [
  ...LEGENDARY,
  ...EPIC,
  ...RARE,
  ...COMMON,
];

export function getWwcBadgeDef(id: string): WwcBadgeDef | undefined {
  return WWC_ACHIEVEMENT_CATALOG.find((d) => d.id === id);
}

export function isWwcBadgeId(id: string): boolean {
  return id.startsWith("wwc_") || !!getWwcBadgeDef(id);
}

export const WWC_STAMP_LABEL: Record<WwcStampKind, string> = {
  visa: "Passport visa",
  ticket: "Stadium ticket",
  globe: "Globe",
  lion: "Lion crest",
  stadium: "Stadium seal",
  brazil: "Brazil seal",
  trophy: "Trophy seal",
  gold_seal: "Gold trophy seal",
};

export const WWC_STAMP_EMOJI: Record<WwcStampKind, string> = {
  visa: "🛂",
  ticket: "🎟️",
  globe: "🌎",
  lion: "🦁",
  stadium: "🏟️",
  brazil: "🇧🇷",
  trophy: "🏆",
  gold_seal: "🥇",
};

/** Counts for docs / UI */
export const WWC_ACHIEVEMENT_COUNTS = {
  common: COMMON.length,
  rare: RARE.length,
  epic: EPIC.length,
  legendary: LEGENDARY.length,
  total: WWC_ACHIEVEMENT_CATALOG.length,
} as const;
