/**
 * Canonical CFB team catalog — stable IDs for favorite-team allegiance.
 * IDs are durable; display names/colors resolve through this module.
 * Generated from FBS roster; IDs are fixed explicit fields (not runtime renames).
 */

import type { SportId } from "@/lib/sports/types";

export type TeamColors = { primary: string; secondary?: string };

export type CanonicalTeam = {
  id: string;
  sportId: SportId;
  name: string;
  conference: string;
  /** Odds / card name match fragments */
  aliases: string[];
  colors: TeamColors;
};

const NEUTRAL: TeamColors = { primary: "#22c55e", secondary: "#0a0a0a" };

/** Explicit CFB catalog — store only `id` in the database. */
export const CFB_TEAM_CATALOG: readonly CanonicalTeam[] = [
  {
    id: "alabama",
    sportId: "cfb",
    name: "Alabama",
    conference: "SEC",
    aliases: ["alabama", "crimson tide"],
    colors: { primary: "#9E1B32", secondary: "#FFFFFF" },
  },
  {
    id: "arkansas",
    sportId: "cfb",
    name: "Arkansas",
    conference: "SEC",
    aliases: ["arkansas", "razorbacks"],
    colors: { primary: "#9D2235", secondary: "#FFFFFF" },
  },
  {
    id: "auburn",
    sportId: "cfb",
    name: "Auburn",
    conference: "SEC",
    aliases: ["auburn", "tigers auburn"],
    colors: { primary: "#0C2340", secondary: "#E87722" },
  },
  {
    id: "florida",
    sportId: "cfb",
    name: "Florida",
    conference: "SEC",
    aliases: ["florida gators", "florida"],
    colors: { primary: "#0021A5", secondary: "#FA4616" },
  },
  {
    id: "georgia",
    sportId: "cfb",
    name: "Georgia",
    conference: "SEC",
    aliases: ["georgia bulldogs", "georgia"],
    colors: { primary: "#BA0C2F", secondary: "#000000" },
  },
  {
    id: "kentucky",
    sportId: "cfb",
    name: "Kentucky",
    conference: "SEC",
    aliases: ["kentucky", "wildcats kentucky"],
    colors: { primary: "#0033A0", secondary: "#FFFFFF" },
  },
  {
    id: "lsu",
    sportId: "cfb",
    name: "LSU",
    conference: "SEC",
    aliases: ["lsu", "louisiana state"],
    colors: { primary: "#461D7C", secondary: "#FDD023" },
  },
  {
    id: "mississippi-state",
    sportId: "cfb",
    name: "Mississippi State",
    conference: "SEC",
    aliases: ["mississippi state", "miss state"],
    colors: { primary: "#660000", secondary: "#FFFFFF" },
  },
  {
    id: "missouri",
    sportId: "cfb",
    name: "Missouri",
    conference: "SEC",
    aliases: ["missouri", "mizzou"],
    colors: { primary: "#F1B82D", secondary: "#000000" },
  },
  {
    id: "oklahoma",
    sportId: "cfb",
    name: "Oklahoma",
    conference: "SEC",
    aliases: ["oklahoma", "sooners"],
    colors: { primary: "#841617", secondary: "#FDF9D8" },
  },
  {
    id: "ole-miss",
    sportId: "cfb",
    name: "Ole Miss",
    conference: "SEC",
    aliases: ["ole miss", "mississippi rebels"],
    colors: { primary: "#CE1126", secondary: "#14213D" },
  },
  {
    id: "south-carolina",
    sportId: "cfb",
    name: "South Carolina",
    conference: "SEC",
    aliases: ["south carolina", "gamecocks"],
    colors: { primary: "#73000A", secondary: "#000000" },
  },
  {
    id: "tennessee",
    sportId: "cfb",
    name: "Tennessee",
    conference: "SEC",
    aliases: ["tennessee", "volunteers", "vols"],
    colors: { primary: "#FF8200", secondary: "#FFFFFF" },
  },
  {
    id: "texas",
    sportId: "cfb",
    name: "Texas",
    conference: "SEC",
    aliases: ["texas longhorns", "texas"],
    colors: { primary: "#BF5700", secondary: "#FFFFFF" },
  },
  {
    id: "texas-am",
    sportId: "cfb",
    name: "Texas A&M",
    conference: "SEC",
    aliases: ["texas a and m", "texas am", "aggies"],
    colors: { primary: "#500000", secondary: "#FFFFFF" },
  },
  {
    id: "vanderbilt",
    sportId: "cfb",
    name: "Vanderbilt",
    conference: "SEC",
    aliases: ["vanderbilt", "commodores"],
    colors: { primary: "#866D4B", secondary: "#000000" },
  },
  {
    id: "illinois",
    sportId: "cfb",
    name: "Illinois",
    conference: "Big Ten",
    aliases: ["illinois", "fighting illini"],
    colors: { primary: "#E84A27", secondary: "#13294B" },
  },
  {
    id: "indiana",
    sportId: "cfb",
    name: "Indiana",
    conference: "Big Ten",
    aliases: ["indiana", "hoosiers"],
    colors: { primary: "#990000", secondary: "#FFFFFF" },
  },
  {
    id: "iowa",
    sportId: "cfb",
    name: "Iowa",
    conference: "Big Ten",
    aliases: ["iowa hawkeyes", "iowa"],
    colors: { primary: "#FFCD00", secondary: "#000000" },
  },
  {
    id: "maryland",
    sportId: "cfb",
    name: "Maryland",
    conference: "Big Ten",
    aliases: ["maryland", "terrapins"],
    colors: { primary: "#E03A3E", secondary: "#FFD520" },
  },
  {
    id: "michigan",
    sportId: "cfb",
    name: "Michigan",
    conference: "Big Ten",
    aliases: ["michigan wolverines", "michigan"],
    colors: { primary: "#00274C", secondary: "#FFCB05" },
  },
  {
    id: "michigan-state",
    sportId: "cfb",
    name: "Michigan State",
    conference: "Big Ten",
    aliases: ["michigan state", "spartans"],
    colors: { primary: "#18453B", secondary: "#FFFFFF" },
  },
  {
    id: "minnesota",
    sportId: "cfb",
    name: "Minnesota",
    conference: "Big Ten",
    aliases: ["minnesota", "golden gophers", "gophers"],
    colors: { primary: "#7A0019", secondary: "#FFCC33" },
  },
  {
    id: "nebraska",
    sportId: "cfb",
    name: "Nebraska",
    conference: "Big Ten",
    aliases: ["nebraska", "cornhuskers", "huskers"],
    colors: { primary: "#E41C38", secondary: "#FFFFFF" },
  },
  {
    id: "northwestern",
    sportId: "cfb",
    name: "Northwestern",
    conference: "Big Ten",
    aliases: ["northwestern", "wildcats northwestern"],
    colors: { primary: "#4E2A84", secondary: "#FFFFFF" },
  },
  {
    id: "ohio-state",
    sportId: "cfb",
    name: "Ohio State",
    conference: "Big Ten",
    aliases: ["ohio state", "buckeyes"],
    colors: { primary: "#BB0000", secondary: "#666666" },
  },
  {
    id: "oregon",
    sportId: "cfb",
    name: "Oregon",
    conference: "Big Ten",
    aliases: ["oregon ducks", "oregon"],
    colors: { primary: "#154733", secondary: "#FEE123" },
  },
  {
    id: "penn-state",
    sportId: "cfb",
    name: "Penn State",
    conference: "Big Ten",
    aliases: ["penn state", "nittany lions"],
    colors: { primary: "#041E42", secondary: "#FFFFFF" },
  },
  {
    id: "purdue",
    sportId: "cfb",
    name: "Purdue",
    conference: "Big Ten",
    aliases: ["purdue", "boilermakers"],
    colors: { primary: "#CEB888", secondary: "#000000" },
  },
  {
    id: "rutgers",
    sportId: "cfb",
    name: "Rutgers",
    conference: "Big Ten",
    aliases: ["rutgers", "scarlet knights"],
    colors: { primary: "#CC0033", secondary: "#FFFFFF" },
  },
  {
    id: "ucla",
    sportId: "cfb",
    name: "UCLA",
    conference: "Big Ten",
    aliases: ["ucla", "bruins"],
    colors: { primary: "#2D68C4", secondary: "#F2A900" },
  },
  {
    id: "usc",
    sportId: "cfb",
    name: "USC",
    conference: "Big Ten",
    aliases: ["usc", "southern california", "southern cal", "trojans"],
    colors: { primary: "#990000", secondary: "#FFC72C" },
  },
  {
    id: "washington",
    sportId: "cfb",
    name: "Washington",
    conference: "Big Ten",
    aliases: ["washington huskies", "washington"],
    colors: { primary: "#4B2E83", secondary: "#B7A57A" },
  },
  {
    id: "wisconsin",
    sportId: "cfb",
    name: "Wisconsin",
    conference: "Big Ten",
    aliases: ["wisconsin", "badgers"],
    colors: { primary: "#C5050C", secondary: "#FFFFFF" },
  },
  {
    id: "boston-college",
    sportId: "cfb",
    name: "Boston College",
    conference: "ACC",
    aliases: ["boston college", "eagles boston"],
    colors: { primary: "#98002E", secondary: "#BC9B6A" },
  },
  {
    id: "california",
    sportId: "cfb",
    name: "California",
    conference: "ACC",
    aliases: ["california", "cal bears", "golden bears"],
    colors: { primary: "#003262", secondary: "#FDB515" },
  },
  {
    id: "clemson",
    sportId: "cfb",
    name: "Clemson",
    conference: "ACC",
    aliases: ["clemson"],
    colors: { primary: "#F56600", secondary: "#522D80" },
  },
  {
    id: "duke",
    sportId: "cfb",
    name: "Duke",
    conference: "ACC",
    aliases: ["duke", "blue devils"],
    colors: { primary: "#003087", secondary: "#FFFFFF" },
  },
  {
    id: "florida-state",
    sportId: "cfb",
    name: "Florida State",
    conference: "ACC",
    aliases: ["florida state", "seminoles", "fsu"],
    colors: { primary: "#782F40", secondary: "#CEB888" },
  },
  {
    id: "georgia-tech",
    sportId: "cfb",
    name: "Georgia Tech",
    conference: "ACC",
    aliases: ["georgia tech", "yellow jackets"],
    colors: { primary: "#B3A369", secondary: "#003057" },
  },
  {
    id: "louisville",
    sportId: "cfb",
    name: "Louisville",
    conference: "ACC",
    aliases: ["louisville", "cardinals louisville"],
    colors: { primary: "#AD0000", secondary: "#000000" },
  },
  {
    id: "miami",
    sportId: "cfb",
    name: "Miami",
    conference: "ACC",
    aliases: ["miami florida", "miami fl", "miami hurricanes", "miami"],
    colors: { primary: "#F47321", secondary: "#005030" },
  },
  {
    id: "nc-state",
    sportId: "cfb",
    name: "NC State",
    conference: "ACC",
    aliases: ["nc state", "north carolina state", "wolfpack"],
    colors: { primary: "#CC0000", secondary: "#FFFFFF" },
  },
  {
    id: "north-carolina",
    sportId: "cfb",
    name: "North Carolina",
    conference: "ACC",
    aliases: ["north carolina", "tar heels", "unc"],
    colors: { primary: "#7BAFD4", secondary: "#13294B" },
  },
  {
    id: "pittsburgh",
    sportId: "cfb",
    name: "Pittsburgh",
    conference: "ACC",
    aliases: ["pittsburgh", "pitt", "panthers pitt"],
    colors: { primary: "#003594", secondary: "#FFB81C" },
  },
  {
    id: "smu",
    sportId: "cfb",
    name: "SMU",
    conference: "ACC",
    aliases: ["smu", "southern methodist"],
    colors: { primary: "#C8102E", secondary: "#0033A0" },
  },
  {
    id: "stanford",
    sportId: "cfb",
    name: "Stanford",
    conference: "ACC",
    aliases: ["stanford", "cardinal"],
    colors: { primary: "#8C1515", secondary: "#FFFFFF" },
  },
  {
    id: "syracuse",
    sportId: "cfb",
    name: "Syracuse",
    conference: "ACC",
    aliases: ["syracuse", "orange"],
    colors: { primary: "#F76900", secondary: "#000E54" },
  },
  {
    id: "virginia",
    sportId: "cfb",
    name: "Virginia",
    conference: "ACC",
    aliases: ["virginia cavaliers", "virginia"],
    colors: { primary: "#232D4B", secondary: "#F84C1E" },
  },
  {
    id: "virginia-tech",
    sportId: "cfb",
    name: "Virginia Tech",
    conference: "ACC",
    aliases: ["virginia tech", "hokies"],
    colors: { primary: "#630031", secondary: "#CF4420" },
  },
  {
    id: "wake-forest",
    sportId: "cfb",
    name: "Wake Forest",
    conference: "ACC",
    aliases: ["wake forest", "demon deacons"],
    colors: { primary: "#9E7E38", secondary: "#000000" },
  },
  {
    id: "arizona",
    sportId: "cfb",
    name: "Arizona",
    conference: "Big 12",
    aliases: ["arizona wildcats", "arizona"],
    colors: { primary: "#CC0033", secondary: "#003366" },
  },
  {
    id: "arizona-state",
    sportId: "cfb",
    name: "Arizona State",
    conference: "Big 12",
    aliases: ["arizona state", "sun devils"],
    colors: { primary: "#8C1D40", secondary: "#FFC627" },
  },
  {
    id: "baylor",
    sportId: "cfb",
    name: "Baylor",
    conference: "Big 12",
    aliases: ["baylor", "bears baylor"],
    colors: { primary: "#154734", secondary: "#FFB81C" },
  },
  {
    id: "byu",
    sportId: "cfb",
    name: "BYU",
    conference: "Big 12",
    aliases: ["byu", "brigham young"],
    colors: { primary: "#002E5D", secondary: "#FFFFFF" },
  },
  {
    id: "cincinnati",
    sportId: "cfb",
    name: "Cincinnati",
    conference: "Big 12",
    aliases: ["cincinnati", "bearcats"],
    colors: { primary: "#E00122", secondary: "#000000" },
  },
  {
    id: "colorado",
    sportId: "cfb",
    name: "Colorado",
    conference: "Big 12",
    aliases: ["colorado buffaloes", "colorado"],
    colors: { primary: "#CFB87C", secondary: "#000000" },
  },
  {
    id: "houston",
    sportId: "cfb",
    name: "Houston",
    conference: "Big 12",
    aliases: ["houston", "cougars houston"],
    colors: { primary: "#C8102E", secondary: "#FFFFFF" },
  },
  {
    id: "iowa-state",
    sportId: "cfb",
    name: "Iowa State",
    conference: "Big 12",
    aliases: ["iowa state", "cyclones"],
    colors: { primary: "#C8102E", secondary: "#F1BE48" },
  },
  {
    id: "kansas",
    sportId: "cfb",
    name: "Kansas",
    conference: "Big 12",
    aliases: ["kansas jayhawks", "kansas"],
    colors: { primary: "#0051BA", secondary: "#E8000D" },
  },
  {
    id: "kansas-state",
    sportId: "cfb",
    name: "Kansas State",
    conference: "Big 12",
    aliases: ["kansas state", "wildcats kansas"],
    colors: { primary: "#512888", secondary: "#FFFFFF" },
  },
  {
    id: "oklahoma-state",
    sportId: "cfb",
    name: "Oklahoma State",
    conference: "Big 12",
    aliases: ["oklahoma state", "cowboys"],
    colors: { primary: "#FF7300", secondary: "#000000" },
  },
  {
    id: "tcu",
    sportId: "cfb",
    name: "TCU",
    conference: "Big 12",
    aliases: ["tcu", "texas christian", "horned frogs"],
    colors: { primary: "#4D1979", secondary: "#A3A9AC" },
  },
  {
    id: "texas-tech",
    sportId: "cfb",
    name: "Texas Tech",
    conference: "Big 12",
    aliases: ["texas tech", "red raiders"],
    colors: { primary: "#CC0000", secondary: "#000000" },
  },
  {
    id: "ucf",
    sportId: "cfb",
    name: "UCF",
    conference: "Big 12",
    aliases: ["ucf", "central florida", "knights"],
    colors: { primary: "#BA9B37", secondary: "#000000" },
  },
  {
    id: "utah",
    sportId: "cfb",
    name: "Utah",
    conference: "Big 12",
    aliases: ["utah utes", "utah"],
    colors: { primary: "#CC0000", secondary: "#FFFFFF" },
  },
  {
    id: "west-virginia",
    sportId: "cfb",
    name: "West Virginia",
    conference: "Big 12",
    aliases: ["west virginia", "mountaineers"],
    colors: { primary: "#002855", secondary: "#EAAA00" },
  },
  {
    id: "notre-dame",
    sportId: "cfb",
    name: "Notre Dame",
    conference: "Independent",
    aliases: ["notre dame", "fighting irish"],
    colors: { primary: "#0C2340", secondary: "#C99700" },
  },
  {
    id: "uconn",
    sportId: "cfb",
    name: "UConn",
    conference: "Independent",
    aliases: ["uconn", "connecticut", "huskies connecticut"],
    colors: { primary: "#000E2F", secondary: "#FFFFFF" },
  },
  {
    id: "umass",
    sportId: "cfb",
    name: "UMass",
    conference: "Independent",
    aliases: ["umass", "massachusetts"],
    colors: NEUTRAL,
  },
  {
    id: "army",
    sportId: "cfb",
    name: "Army",
    conference: "Group of 5",
    aliases: ["army", "black knights"],
    colors: { primary: "#D4BF91", secondary: "#000000" },
  },
  {
    id: "east-carolina",
    sportId: "cfb",
    name: "East Carolina",
    conference: "Group of 5",
    aliases: ["east carolina", "pirates"],
    colors: NEUTRAL,
  },
  {
    id: "florida-atlantic",
    sportId: "cfb",
    name: "Florida Atlantic",
    conference: "Group of 5",
    aliases: ["florida atlantic", "fau", "owls fau"],
    colors: NEUTRAL,
  },
  {
    id: "memphis",
    sportId: "cfb",
    name: "Memphis",
    conference: "Group of 5",
    aliases: ["memphis", "tigers memphis"],
    colors: { primary: "#003087", secondary: "#898D8D" },
  },
  {
    id: "navy",
    sportId: "cfb",
    name: "Navy",
    conference: "Group of 5",
    aliases: ["navy", "midshipmen"],
    colors: { primary: "#00205B", secondary: "#C5B783" },
  },
  {
    id: "north-texas",
    sportId: "cfb",
    name: "North Texas",
    conference: "Group of 5",
    aliases: ["north texas", "mean green"],
    colors: NEUTRAL,
  },
  {
    id: "rice",
    sportId: "cfb",
    name: "Rice",
    conference: "Group of 5",
    aliases: ["rice", "owls rice"],
    colors: NEUTRAL,
  },
  {
    id: "south-florida",
    sportId: "cfb",
    name: "South Florida",
    conference: "Group of 5",
    aliases: ["south florida", "usf", "bulls usf"],
    colors: NEUTRAL,
  },
  {
    id: "temple",
    sportId: "cfb",
    name: "Temple",
    conference: "Group of 5",
    aliases: ["temple", "owls temple"],
    colors: NEUTRAL,
  },
  {
    id: "tulane",
    sportId: "cfb",
    name: "Tulane",
    conference: "Group of 5",
    aliases: ["tulane", "green wave"],
    colors: { primary: "#006747", secondary: "#418FDE" },
  },
  {
    id: "tulsa",
    sportId: "cfb",
    name: "Tulsa",
    conference: "Group of 5",
    aliases: ["tulsa", "golden hurricane"],
    colors: NEUTRAL,
  },
  {
    id: "utsa",
    sportId: "cfb",
    name: "UTSA",
    conference: "Group of 5",
    aliases: ["utsa", "texas san antonio", "roadrunners"],
    colors: NEUTRAL,
  },
  {
    id: "charlotte",
    sportId: "cfb",
    name: "Charlotte",
    conference: "Group of 5",
    aliases: ["charlotte", "49ers"],
    colors: NEUTRAL,
  },
  {
    id: "air-force",
    sportId: "cfb",
    name: "Air Force",
    conference: "Group of 5",
    aliases: ["air force", "falcons air"],
    colors: { primary: "#0033A0", secondary: "#8A8D8F" },
  },
  {
    id: "boise-state",
    sportId: "cfb",
    name: "Boise State",
    conference: "Group of 5",
    aliases: ["boise state", "broncos"],
    colors: { primary: "#0033A0", secondary: "#D64309" },
  },
  {
    id: "colorado-state",
    sportId: "cfb",
    name: "Colorado State",
    conference: "Group of 5",
    aliases: ["colorado state", "rams colorado"],
    colors: NEUTRAL,
  },
  {
    id: "fresno-state",
    sportId: "cfb",
    name: "Fresno State",
    conference: "Group of 5",
    aliases: ["fresno state", "bulldogs fresno"],
    colors: { primary: "#DB0032", secondary: "#002E6D" },
  },
  {
    id: "hawaii",
    sportId: "cfb",
    name: "Hawaii",
    conference: "Group of 5",
    aliases: ["hawaii", "rainbow warriors"],
    colors: NEUTRAL,
  },
  {
    id: "nevada",
    sportId: "cfb",
    name: "Nevada",
    conference: "Group of 5",
    aliases: ["nevada", "wolf pack nevada"],
    colors: NEUTRAL,
  },
  {
    id: "new-mexico",
    sportId: "cfb",
    name: "New Mexico",
    conference: "Group of 5",
    aliases: ["new mexico", "lobos"],
    colors: NEUTRAL,
  },
  {
    id: "san-diego-state",
    sportId: "cfb",
    name: "San Diego State",
    conference: "Group of 5",
    aliases: ["san diego state", "aztecs"],
    colors: { primary: "#A89968", secondary: "#000000" },
  },
  {
    id: "san-jose-state",
    sportId: "cfb",
    name: "San Jose State",
    conference: "Group of 5",
    aliases: ["san jose state", "sjsu", "spartans san jose"],
    colors: NEUTRAL,
  },
  {
    id: "unlv",
    sportId: "cfb",
    name: "UNLV",
    conference: "Group of 5",
    aliases: ["unlv", "rebels unlv"],
    colors: { primary: "#CF0A2C", secondary: "#B3B5B8" },
  },
  {
    id: "utah-state",
    sportId: "cfb",
    name: "Utah State",
    conference: "Group of 5",
    aliases: ["utah state", "aggies utah"],
    colors: NEUTRAL,
  },
  {
    id: "wyoming",
    sportId: "cfb",
    name: "Wyoming",
    conference: "Group of 5",
    aliases: ["wyoming", "cowboys wyoming"],
    colors: NEUTRAL,
  },
  {
    id: "akron",
    sportId: "cfb",
    name: "Akron",
    conference: "Group of 5",
    aliases: ["akron", "zips"],
    colors: NEUTRAL,
  },
  {
    id: "ball-state",
    sportId: "cfb",
    name: "Ball State",
    conference: "Group of 5",
    aliases: ["ball state", "cardinals ball"],
    colors: NEUTRAL,
  },
  {
    id: "bowling-green",
    sportId: "cfb",
    name: "Bowling Green",
    conference: "Group of 5",
    aliases: ["bowling green", "falcons bowling"],
    colors: NEUTRAL,
  },
  {
    id: "buffalo",
    sportId: "cfb",
    name: "Buffalo",
    conference: "Group of 5",
    aliases: ["buffalo", "bulls buffalo"],
    colors: NEUTRAL,
  },
  {
    id: "central-michigan",
    sportId: "cfb",
    name: "Central Michigan",
    conference: "Group of 5",
    aliases: ["central michigan", "chippewas"],
    colors: NEUTRAL,
  },
  {
    id: "eastern-michigan",
    sportId: "cfb",
    name: "Eastern Michigan",
    conference: "Group of 5",
    aliases: ["eastern michigan", "eagles eastern"],
    colors: NEUTRAL,
  },
  {
    id: "kent-state",
    sportId: "cfb",
    name: "Kent State",
    conference: "Group of 5",
    aliases: ["kent state", "golden flashes"],
    colors: NEUTRAL,
  },
  {
    id: "miami-oh",
    sportId: "cfb",
    name: "Miami (OH)",
    conference: "Group of 5",
    aliases: ["miami ohio", "miami oh", "redhawks"],
    colors: NEUTRAL,
  },
  {
    id: "northern-illinois",
    sportId: "cfb",
    name: "Northern Illinois",
    conference: "Group of 5",
    aliases: ["northern illinois", "hiu", "huskies northern"],
    colors: NEUTRAL,
  },
  {
    id: "ohio",
    sportId: "cfb",
    name: "Ohio",
    conference: "Group of 5",
    aliases: ["ohio bobcats", "ohio university"],
    colors: NEUTRAL,
  },
  {
    id: "toledo",
    sportId: "cfb",
    name: "Toledo",
    conference: "Group of 5",
    aliases: ["toledo", "rockets"],
    colors: NEUTRAL,
  },
  {
    id: "western-michigan",
    sportId: "cfb",
    name: "Western Michigan",
    conference: "Group of 5",
    aliases: ["western michigan", "broncos western"],
    colors: NEUTRAL,
  },
  {
    id: "appalachian-state",
    sportId: "cfb",
    name: "Appalachian State",
    conference: "Group of 5",
    aliases: ["appalachian state", "app state", "mountaineers app"],
    colors: { primary: "#000000", secondary: "#FFCC00" },
  },
  {
    id: "arkansas-state",
    sportId: "cfb",
    name: "Arkansas State",
    conference: "Group of 5",
    aliases: ["arkansas state", "red wolves"],
    colors: NEUTRAL,
  },
  {
    id: "coastal-carolina",
    sportId: "cfb",
    name: "Coastal Carolina",
    conference: "Group of 5",
    aliases: ["coastal carolina", "chanticleers"],
    colors: NEUTRAL,
  },
  {
    id: "georgia-southern",
    sportId: "cfb",
    name: "Georgia Southern",
    conference: "Group of 5",
    aliases: ["georgia southern", "eagles georgia southern"],
    colors: NEUTRAL,
  },
  {
    id: "georgia-state",
    sportId: "cfb",
    name: "Georgia State",
    conference: "Group of 5",
    aliases: ["georgia state", "panthers georgia state"],
    colors: NEUTRAL,
  },
  {
    id: "james-madison",
    sportId: "cfb",
    name: "James Madison",
    conference: "Group of 5",
    aliases: ["james madison", "jmu", "dukes"],
    colors: NEUTRAL,
  },
  {
    id: "louisiana",
    sportId: "cfb",
    name: "Louisiana",
    conference: "Group of 5",
    aliases: ["louisiana ragin", "louisiana lafayette", "ul lafayette", "ragin cajuns"],
    colors: NEUTRAL,
  },
  {
    id: "marshall",
    sportId: "cfb",
    name: "Marshall",
    conference: "Group of 5",
    aliases: ["marshall", "thundering herd"],
    colors: NEUTRAL,
  },
  {
    id: "old-dominion",
    sportId: "cfb",
    name: "Old Dominion",
    conference: "Group of 5",
    aliases: ["old dominion", "monarchs"],
    colors: NEUTRAL,
  },
  {
    id: "south-alabama",
    sportId: "cfb",
    name: "South Alabama",
    conference: "Group of 5",
    aliases: ["south alabama", "jaguars south"],
    colors: NEUTRAL,
  },
  {
    id: "southern-miss",
    sportId: "cfb",
    name: "Southern Miss",
    conference: "Group of 5",
    aliases: ["southern miss", "southern mississippi", "golden eagles"],
    colors: NEUTRAL,
  },
  {
    id: "texas-state",
    sportId: "cfb",
    name: "Texas State",
    conference: "Group of 5",
    aliases: ["texas state", "bobcats texas"],
    colors: NEUTRAL,
  },
  {
    id: "troy",
    sportId: "cfb",
    name: "Troy",
    conference: "Group of 5",
    aliases: ["troy", "trojans troy"],
    colors: NEUTRAL,
  },
  {
    id: "ul-monroe",
    sportId: "cfb",
    name: "UL Monroe",
    conference: "Group of 5",
    aliases: ["ul monroe", "louisiana monroe", "warhawks"],
    colors: NEUTRAL,
  },
  {
    id: "fiu",
    sportId: "cfb",
    name: "FIU",
    conference: "Group of 5",
    aliases: ["fiu", "florida international"],
    colors: NEUTRAL,
  },
  {
    id: "jacksonville-state",
    sportId: "cfb",
    name: "Jacksonville State",
    conference: "Group of 5",
    aliases: ["jacksonville state", "gamecocks jax"],
    colors: NEUTRAL,
  },
  {
    id: "kennesaw-state",
    sportId: "cfb",
    name: "Kennesaw State",
    conference: "Group of 5",
    aliases: ["kennesaw state", "owls kennesaw"],
    colors: NEUTRAL,
  },
  {
    id: "liberty",
    sportId: "cfb",
    name: "Liberty",
    conference: "Group of 5",
    aliases: ["liberty", "flames"],
    colors: NEUTRAL,
  },
  {
    id: "louisiana-tech",
    sportId: "cfb",
    name: "Louisiana Tech",
    conference: "Group of 5",
    aliases: ["louisiana tech", "bulldogs la tech"],
    colors: NEUTRAL,
  },
  {
    id: "middle-tennessee",
    sportId: "cfb",
    name: "Middle Tennessee",
    conference: "Group of 5",
    aliases: ["middle tennessee", "mtsu", "blue raiders"],
    colors: NEUTRAL,
  },
  {
    id: "new-mexico-state",
    sportId: "cfb",
    name: "New Mexico State",
    conference: "Group of 5",
    aliases: ["new mexico state", "aggies nmsu"],
    colors: NEUTRAL,
  },
  {
    id: "sam-houston",
    sportId: "cfb",
    name: "Sam Houston",
    conference: "Group of 5",
    aliases: ["sam houston", "bearkats"],
    colors: NEUTRAL,
  },
  {
    id: "utep",
    sportId: "cfb",
    name: "UTEP",
    conference: "Group of 5",
    aliases: ["utep", "texas el paso", "miners"],
    colors: NEUTRAL,
  },
  {
    id: "western-kentucky",
    sportId: "cfb",
    name: "Western Kentucky",
    conference: "Group of 5",
    aliases: ["western kentucky", "wku", "hilltoppers"],
    colors: NEUTRAL,
  },
] as const;

const BY_ID = new Map(CFB_TEAM_CATALOG.map((t) => [t.id, t]));

export function listCfbCatalog(): CanonicalTeam[] {
  return [...CFB_TEAM_CATALOG].sort((a, b) => a.name.localeCompare(b.name));
}

export function getCfbTeamById(id: string | null | undefined): CanonicalTeam | null {
  if (!id) return null;
  return BY_ID.get(id) ?? null;
}

export function isValidCfbTeamId(id: string): boolean {
  return BY_ID.has(id);
}

/**
 * Confident match of a card/odds team name to catalog.
 * Requires a solid alias or name hit — partial uncertain matches return null.
 */
export function matchCfbTeamConfident(rawName: string): CanonicalTeam | null {
  const n = normalize(rawName);
  if (!n || n.length < 3) return null;
  let best: { team: CanonicalTeam; score: number } | null = null;
  for (const t of CFB_TEAM_CATALOG) {
    const candidates = [t.name, ...t.aliases];
    for (const c of candidates) {
      const k = normalize(c);
      if (!k) continue;
      if (n === k) {
        const score = 1000 + k.length;
        if (!best || score > best.score) best = { team: t, score };
        continue;
      }
      // whole-word / full-phrase containment only for longer keys
      if (k.length >= 5 && (n.includes(k) || k.includes(n))) {
        // reject weak short containment like "miami" alone vs miami-oh
        if (k.length < 6 && n !== k) continue;
        const score = 100 + k.length;
        if (!best || score > best.score) best = { team: t, score };
      }
    }
  }
  // Require high confidence
  if (!best || best.score < 105) return null;
  return best.team;
}

function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/\./g, "")
    .replace(/&/g, "and")
    .replace(/\(oh\)/g, "ohio")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
